<a href="https://colab.research.google.com/github/rayamalyshkina/Playground/blob/hw_3/Practice_3_Malyshkina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import numpy as np

In [27]:
path = 'drive/MyDrive/Colab Notebooks/train.csv'

# Вывод датасета

In [28]:
base_set = pd.read_csv(path)
base_set.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Основная информация о датасете

In [29]:
base_set.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [70]:
base_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  FullName     891 non-null    object
 13  FirstName    891 non-null    object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.6+ KB

# Выживаемость пассажиров внутри класса обслуживания

Доля выживших пассажиров среди всех пассажиров данного класса обслуживания:

In [30]:
base_set.groupby('Pclass')['Survived'].mean() * 100

Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

Доля пассажиров каждого класса среди всех выживших:

In [31]:
base_set.groupby('Pclass')['Survived'].sum() / base_set['Survived'].sum() * 100

Pclass
1    39.766082
2    25.438596
3    34.795322
Name: Survived, dtype: float64

# Самые популярные мужское и женское имена

In [48]:
base_set['FullName'] = (base_set['Name'].str.split(',').str[1]
.str.split('.').str[1])

base_set['FirstName'] = np.where(
    base_set['FullName'].str.contains('(', regex=False),

    base_set['FullName'].str.split('(').str[1]
    .str.split(' ').str[0]
    .str.strip(),

    base_set['FullName'].str.split(' ').str[1]
    .str.strip()
)

top_female_name = base_set[base_set['Sex'] == 'female']['FirstName'].value_counts().idxmax()
top_male_name = base_set[base_set['Sex'] == 'male']['FirstName'].value_counts().idxmax()

print(f'The most popular female name was {top_female_name} and the most popular male name was {top_male_name}')

The most popular female name was Anna and the most popular male name was William

In [53]:
top_names = (
    base_set
    .groupby('Sex')['FirstName']
    .agg(lambda x: x.value_counts().idxmax())
)

top_names

Sex
female       Anna
male      William
Name: FirstName, dtype: object

# Самые популярные мужское и женское имена по классам обслуживания

In [54]:
top_names_pclass = (
    base_set
    .groupby(['Pclass', 'Sex'])['FirstName']
    .agg(lambda x: x.value_counts().idxmax())
)

top_names_pclass

Pclass  Sex
1       female    Elizabeth
        male        William
2       female    Elizabeth
        male        William
3       female         Anna
        male        William
Name: FirstName, dtype: object

# Пассажиры старше 44

In [71]:
base_set[base_set['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FullName,FirstName
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy J,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,(Mary D Kingcome),Mary
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward H,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Henry Sleeper (Myna Haxtun),Myna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,Peter Denis,Peter
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Frederick Joel (Margaret Welles Barron),Margaret
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Richard Leonard (Sallie Monypeny),Sallie
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,Victor,Victor
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Thomas Jr (Lily Alexenia Wilson),Lily

# Пассажиры-мужчины младше 44

In [72]:
base_set[(base_set['Age'] < 44) & (base_set['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FullName,FirstName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S,Owen Harris,Owen
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050,NaN,S,William Henry,William
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.075,NaN,S,Gosta Leonard,Gosta
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.050,NaN,S,William Henry,William
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,Anders Johan,Anders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,S,Frederick James,Frederick
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,S,Henry Jr,Henry
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S,Juozas,Juozas
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C,Karl Howell,Karl
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q,Patrick,Patrick

# Кабины по вместимости

In [73]:
places_per_cabin = base_set['Cabin'].value_counts()

cabin_sizes_count = places_per_cabin.value_counts()

cabin_sizes_count

count
1    101
2     38
3      5
4      3
Name: count, dtype: int64